InsuranceOrg/force-app/main/default/objects/Asset/fields/Latest_Open_Claim__c.field-meta.xml
<CustomField>
    <fullName>Latest_Open_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Open Claim</label>
    <referenceTo>vlocity_ins__InsuranceClaim__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

InsuranceOrg/force-app/main/default/objects/vlocity_ins__InsuranceClaim__c/vlocity_ins__InsuranceClaim__c.object-meta.xml
<CustomObject>
    <description>A claim is a formal request made by an insured party to an insurance company for coverage or compensation for a covered loss or policy event. Claims may cover comprehensive medical exams, automotive repairs or even death benefits.</description>
    <label>Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsuranceOrg/force-app/main/default/objects/vlocity_ins__InsuranceClaim__c/fields/vlocity_ins__ClaimStatus__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__ClaimStatus__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Adjuster Review</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Confirm Coverage</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InsuranceOrg/force-app/main/default/objects/vlocity_ins__InsuranceClaim__c/fields/vlocity_ins__PrimaryPolicyAssetId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_ins__PrimaryPolicyAssetId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Policy</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>PrimaryClaims</relationshipName>
    <type>Lookup</type>
</CustomField>

Manifest/main/default/classes/LatestOpenClaimOnAsset.cls
public class LatestOpenClaimOnAsset {
  public static void updateAssets (List<vlocity_ins__InsuranceClaim__c > newClaims){
        
        Set<Id> claimIds = new Set<Id>();
        for( vlocity_ins__InsuranceClaim__c cl: newClaims){
            claimIds.add(cl.Id);
        }
        
        List<vlocity_ins__InsuranceClaim__c > reorder = [select Id, vlocity_ins__PrimaryPolicyAssetId__c 
        from vlocity_ins__InsuranceClaim__c 
        where vlocity_ins__ClaimStatus__c = 'Open' and Id in :claimIds and vlocity_ins__PrimaryPolicyAssetId__c  != null  order by lastModifiedDate ];
        
        if(reorder.size()>0){
            Map<Id,vlocity_ins__InsuranceClaim__c> assetClaimMap = new Map<Id,vlocity_ins__InsuranceClaim__c>();
            
             for( vlocity_ins__InsuranceClaim__c c: newClaims){
                 assetClaimMap.put(c.vlocity_ins__PrimaryPolicyAssetId__c,c);
             }
            
             List<Asset> assetList = [select Id, Latest_Open_Claim__c from Asset where Id in :assetClaimMap.keySet()];
             
             if(assetList.size()>0){
                   for(Asset a : assetList){
                       a.Latest_Open_claim__c = assetClaimMap.get(a.Id).Id;
                   }
                   
                   update assetList;
                 
             }
            
        }
        
      
  }
}